data_dir: /tank/new_dataset/
default:
  overwrite: False
  video_name: trafficcam_1
instances:
- method: gt
  qp: 24
  resolution: 1.0
- method: mpeg
  qp:
  - 36
  - 26
  resolution: 0.8
- batch_size: 15
  high_qp: 26
  high_res: 0.8
  low_qp: 36
  low_res: 0.8
  method: dds
  objfilter_iou: 0.3
  prune_score: 0.5
  rpn_enlarge_ratio: 0.0
  size_obj: 0.01
mode: emulation
